language: generic
sudo : required

services: 
  - docker

before_install: 
  - docker build -t amirsha99/client_test -f ./client/Dockerfile.dev ./client

script:   
  - docker run -e CI=true amirsha99/client_test npm test -- --coverage

after_success:
  - docker build -t amirsha99/multi-client ./client
  - docker build -t amirsha99/multi-nginx ./nginx
  - docker build -t amirsha99/multi-server ./server
  - docker build -t amirsha99/multi-worker ./worker

  #docker login  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push amirsha99/multi-client
  - docker push amirsha99/multi-nginx
  - docker push amirsha99/multi-server
  - docker push amirsha99/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-529438765371'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  